### ISSUE TITLE
How to modify the character model

### ISSUE THREAD

**Issue by dyp159** [heyuanYao-pku/Control-VAE#10]
This is a question instead of issue.
I tried to modify the character to employ the model into a more generalizable case. 
I have noticed the `world.json` as the scene file for ODEsimu Backend. 
I don't want to only work on that scene file. How can I visualize&modify `world.json` easily? Which engine should I use to load it? 
Thanks for your help!

**Comment by heyuanYao-pku** [comment]
Actually, we built this character using a custom Unity pipeline. However, this pipeline cannot be open-sourced at the moment, as I don't have the authority to do so—I'm just a user. The owner might consider open-sourcing it in the future, and if that happens, I will add a link to the project.

**Comment by Entity363** [comment]
Would it be possible to get more information on how you implemented your pipeline or what unity system you used for it?
