### ISSUE TITLE
想问下已经安装了对应的cython和setuptools，还会出现这种报错是环境哪边出了问题吗

### ISSUE THREAD

**Issue by Tinazyt** [heyuanYao-pku/Control-VAE#11]
[controlvae环境报错.docx](https://github.com/user-attachments/files/16118176/controlvae.docx)

**Comment by heyuanYao-pku** [comment]
您好，根据docx图片里的提示，pip似乎没能找到cmake能用的complier，比如windows 上的visual studio。
 请检查下是否安装了VS，以及环境变量是否正确。
我目前没遇到过这个问题， 一个可能有用的链接是https://stackoverflow.com/questions/32801638/cmake-error-at-cmakelists-txt30-project-no-cmake-c-compiler-could-be-found

**Comment by Tinazyt** [comment]
非常感谢您的回复，我再检查检查
