### ISSUE TITLE
Data Configuration Transfermation Questions

### ISSUE THREAD

**Issue by motor-x** [heyuanYao-pku/Control-VAE#12]
Hi,

I am new to the ODE simulator. I was wondering: how to transfer your original data (rigid state) to robot's DOF state (e.g., position or velocity)? 

This is important to us, because we want to use isaac gym to replace your original ODE simulator, but keep using your dataset. Thus, we need to figure out the mapping, but we got stuck. 

Look forward to your response, and thank you very much!

**Comment by heyuanYao-pku** [comment]
The dataset we used is retargeted LaFAN dataset. So what you need is actually the mapping between LaFAN character and your robot character in isaac gym. This mapping needs to be defined manually.

I recommand to refer to the repo (https://github.com/xupei0610/CompositeMotion) which uses LaFAN data in the isaac enviroment.

**Comment by motor-x** [comment]
Awesome! Thank you so much for your quick reply!

**Comment by motor-x** [comment]
Just one follow-up question, it seems (https://github.com/xupei0610/CompositeMotion) requires a [json](https://github.com/xupei0610/CompositeMotion/blob/main/assets/motions/locomotion/lafan1_run1_subject5_160_2105_mirror.json) or [pkl](https://github.com/xupei0610/CompositeMotion/blob/main/assets/motions_binary/locomotion/crouch_lafan1_walk3_subject5_2490_2735_mirror.pkl) file. Do you have any idea about how to generate these files from the original LaFAN dataset?

Thank you so much!

**Comment by motor-x** [comment]
As we would like to reproduce your work with isaac gym, **could you please let us know the exact dataset you used from LaFAN?** 

For example, LaFAN has:

walk1_subject1.bvh
walk1_subject2.bvh
walk1_subject5.bvh
...

Did you use all of them for your walk task? Thank you!
