### ISSUE TITLE
Data generation

### ISSUE THREAD

**Issue by Hardwarize** [heyuanYao-pku/Control-VAE#14]
Hi, thanks for sharing your work. I'm trying to fully understand the control-VAE technique but I'm not able to understand how to generate the `runwalkjumpgetup.pickle` dataset.
Could you share the script or required command?

Thanks in advance for your help

**Comment by heyuanYao-pku** [comment]
Hello, I updated build_motion_dataset.py, you can obtain the pickle by simply running it. Please check it.
