### ISSUE TITLE
use git-lfs instead of committing binary files

### ISSUE THREAD

**Issue by GCCFeli** [heyuanYao-pku/Control-VAE#2]
Use [git-lfs](https://git-lfs.com/) will make the repository cleaner.
Git Large File Storage (LFS) replaces large files such as audio samples, videos, datasets, and graphics with text pointers inside Git, while storing the file contents on a remote server like GitHub.com or GitHub Enterprise.

**Comment by heyuanYao-pku** [comment]
updated, thx
