### ISSUE TITLE
Weights for losses

### ISSUE THREAD

**Issue by pjanime** [heyuanYao-pku/Control-VAE#5]
Are the weights for different losses used to train joystick control defined here: https://github.com/heyuanYao-pku/Control-VAE/blob/main/PlayGround/joystick_playground.py#L323 ?
Why is the weight for speed loss set to 0?

**Comment by heyuanYao-pku** [comment]
Yes, you are right, the weights are define here.
In our experiments, we observed a certain conflict between the trained directional loss and velocity loss, especially when the character is turning. In such cases, the character must choose between maintaining speed or rapidly adjusting direction. The released joystick training code is merely a test case, and you can balance the weights of these two aspects according to your specific needs.

**Comment by pjanime** [comment]
Thanks for your response, I will try adjusting the weights.
