### ISSUE TITLE
need help with data processing for training from scratch

### ISSUE THREAD

**Issue by zzzark** [heyuanYao-pku/Control-VAE#6]
@heyuanYao-pku Thank you for providing us the source code! I am trying to process the data with [lafan1 dataset](https://github.com/ubisoft/ubisoft-laforge-animation-dataset/) with the following code:

```python

# some imports ...

scene_fname = 'Data/Misc/world.json'
SceneLoader = JsonSceneLoader()
scene = SceneLoader.file_load(scene_fname)
character = scene.characters[0]

dataset = MotionDataSet(fps=20)
dataset.add_folder_bvh("Data/ReferenceData/runwalkjumpgetup", character)

```

However, it seems that the names of the character's joints do not match what is in the BVH data. And I encountered an error `KeyError: 'pelvis_lowerback'` in [this file](https://github.com/heyuanYao-pku/Control-VAE/blob/main/ModifyODESrc/VclSimuBackend.pyx#L16722). Is there any solution to work around this problem?

**Comment by zzzark** [comment]
@heyuanYao-pku Thank you for your quick reply! Unfortunately I failed to download the BVH data in `https://github.com/heyuanYao-pku/Control-VAE/tree/main/Data/ReferenceData/runwalkjumpgetup` due to the quota limit:

```bash
$ git-lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth 
should purchase more data packs to restore access.
```

Could you please provide a shorter BVH template (only the skeleton's topology) for reference?

**Comment by heyuanYao-pku** [comment]
@zzzark Hi, I've updated the repo and shifted LFS files to regular Git. Please check it out. For any issues, I'll be on it tomorrow.

**Comment by zzzark** [comment]
@heyuanYao-pku Hi, I received the BVH data you provided, but the mapping of the joints doesn't seem very obvious. For instance, the number of joints and joint offsets in the original lafan1 data doesn't precisely match the retargeted data. Could you please share the code or tool you used to retarget the motion data?

**Comment by heyuanYao-pku** [comment]
@zzzark Thanks for reaching out about the BVH data. Actually, we started the project using data that had already been retargeted by previous teams, so we don't have a specific tool or code to share for that process.

**Comment by zzzark** [comment]
OK, I'll try these tools.
