### ISSUE TITLE
Link for pretrained model is not work

### ISSUE THREAD

**Issue by JeonghyunNam** [heyuanYao-pku/Control-VAE#7]
Hello. Thanks for your great work.
As described in the title, I cannot download the pretrained-model with the link in the ReadME.
Could you check it please?

**Comment by heyuanYao-pku** [comment]
hello, I check the links. 
Onedrive link is fine and PKU disk link is lost. It's updated now, please have a check :)

**Comment by JeonghyunNam** [comment]
I don't know why but connection time-out occurs for one-drive link.
but updated PKU disk link works! Thanks you for fast reply
