### ISSUE TITLE
Why my training result is bad by simply executing the given command

### ISSUE THREAD

**Issue by dyp159** [heyuanYao-pku/Control-VAE#8]
Thank you for the readable codes. 

I executed the training command as outlined in the README.md. However, the model's performance after 20,000 iterations differs from that of the pretrained model when running random_playground.py. The robot frequently falls and has difficulty standing up, consistently failing to do so. I trained the model using the default settings. What could be the issue?

Here is my log and model data. 
https://cloud.tsinghua.edu.cn/d/6cc1547cfec3406286b5/

**Comment by heyuanYao-pku** [comment]
I reviewed the checkpoint you submitted, and it does seem to be a bit odd... I ran PlayGround/track_playground.py, and it seems like the characters can't even reconstruct motions. This might be due to some version inconsistencies in the code, and I'm attempting to retrain. Please give me a little time.

**Comment by heyuanYao-pku** [comment]
By the way, could you provide me with some of the BVH outputs from the training process? Because from what I've seen, your training curves seem normal, but there seems to be an issue with the output strategy.

**Comment by heyuanYao-pku** [comment]
Hi! I found a bug that may cause this. In the ControlVAE.yml, it set env: substep to 1, actually, this should be 6. 
Here is the right version:
env:
  scene_fname: ./Data/Misc/world.json
  fps: 20
  substep: 6

I'm retraining with this version now. If that works, I'll make an update. Sorry for  the inconvenience

**Comment by dyp159** [comment]
I have uploaded the training BVH files to that cloud. I am retraining with your modification, too.

**Comment by heyuanYao-pku** [comment]
@dyp159 Hi, I've finished training, and the result seems right this time. Did you get the right output?

**Comment by dyp159** [comment]
Yes! Thanks for your efficient replies!
