### ISSUE TITLE
Problem encountered while running setup for ModifyODESrc

### ISSUE THREAD

**Issue by 1279265865** [heyuanYao-pku/Control-VAE#9]
We encountered the following issues while deploying your project, which resulted in errors on multiple platforms (Win11 & MacOS). Specifically, we received the following error when running setup.py in the ModifyODESrc directory. We hope to get your assistance to successfully run the project.

× python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [105 lines of output]
        running develop
        running egg_info
        creating ode.egg-info
        writing ode.egg-info\PKG-INFO
        writing dependency_links to ode.egg-info\dependency_links.txt
        writing top-level names to ode.egg-info\top_level.txt
        writing manifest file 'ode.egg-info\SOURCES.txt'
        dependency D:\Conda\envs\control-vae\lib\site-packages\numpy\core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
        dependency D:\Conda\envs\control-vae\lib\site-packages\numpy\core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
        dependency D:\Conda\envs\control-vae\lib\site-packages\numpy\core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
        dependency D:\Conda\envs\control-vae\lib\site-packages\numpy\core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
        dependency D:\Conda\envs\control-vae\lib\site-packages\numpy\core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
        dependency D:\DeskTopFile\Control-VAE-main\ModifyODESrc\Utils\MixQuaternion.h won't be automatically included in the manifest: the path must be relative
        dependency D:\DeskTopFile\Control-VAE-main\ModifyODESrc\Utils\PDControlAdd.h won't be automatically included in the manifest: the path must be relative
        dependency D:\DeskTopFile\Control-VAE-main\ModifyODESrc\Utils\QuaternionWithGrad.h won't be automatically included in the manifest: the path must be relative
        dependency D:\DeskTopFile\Control-VAE-main\ModifyODESrc\Utils\joint_local_quat_batch.h won't be automatically included in the manifest: the path must be relative
        dependency D:\DeskTopFile\Control-VAE-main\ModifyODESrc\include\drawstuff\drawstuffWrapper.h won't be automatically included in the manifest: the path must be relative
        dependency D:\DeskTopFile\Control-VAE-main\ModifyODESrc\include\ode\ode.h won't be automatically included in the manifest: the path must be relative
        dependency D:\DeskTopFile\Control-VAE-main\ThirdParty\EigenExtension\EigenBindingWrapper.h won't be automatically included in the manifest: the path must be relative
        dependency D:\DeskTopFile\Control-VAE-main\ThirdParty\EigenExtension\LinearEquSolve.h won't be automatically included in the manifest: the path must be relative
        reading manifest file 'ode.egg-info\SOURCES.txt'
        writing manifest file 'ode.egg-info\SOURCES.txt'
        running build_ext
        -- Building for: NMake Makefiles
        CMake Warning (dev) at CMakeLists.txt:1 (PROJECT):
          cmake_minimum_required() should be called prior to this top-level project()
          call.  Please see the cmake-commands(7) manual for usage documentation of
          both commands.
        This warning is for project developers.  Use -Wno-dev to suppress it.

        CMake Error at CMakeLists.txt:1 (PROJECT):
          Running

           'nmake' '-?'

          failed with:

           绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82

        CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
        CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
        -- Configuring incomplete, errors occurred!
        D:\Conda\envs\control-vae\lib\site-packages\setuptools\dist.py:318: InformationOnly: Normalizing '0.12.2024.05.14.14.19.43' to '0.12.2024.5.14.14.19.43'
          self.metadata.version = self._normalize_version(self.metadata.version)
        D:\Conda\envs\control-vae\lib\site-packages\setuptools\command\develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!

                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.

                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************

        !!
          easy_install.initialize_options(self)
        D:\Conda\envs\control-vae\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!

                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.

                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************

        !!
          self.initialize_options()
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "D:\DeskTopFile\Control-VAE-main\ModifyODESrc\setup.py", line 94, in <module>
            setup(
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\__init__.py", line 104, in setup
            return distutils.core.setup(**attrs)
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
            return run_commands(dist)
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
            dist.run_commands()
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\dist.py", line 967, in run_command
            super().run_command(command)
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\command\develop.py", line 34, in run
            self.install_for_development()
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\command\develop.py", line 111, in install_for_development
            self.run_command('build_ext')
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
            self.distribution.run_command(command)
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\dist.py", line 967, in run_command
            super().run_command(command)
          File "D:\Conda\envs\control-vae\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
            cmd_obj.run()
          File "D:\DeskTopFile\Control-VAE-main\ModifyODESrc\setup.py", line 32, in run
            self.cmake_build(ode_dir)
          File "D:\DeskTopFile\Control-VAE-main\ModifyODESrc\setup.py", line 52, in cmake_build
            subprocess.check_call(['cmake', cmake_path] + cmake_args, cwd=ode_dir, env=env)
          File "D:\Conda\envs\control-vae\lib\subprocess.py", line 364, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['cmake', 'D:\\DeskTopFile\\Control-VAE-main\\ModifyODESrc', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\DeskTopFile\\Control-VAE-main\\ModifyODESrc', '-DCMAKE_INSTALL_PREFIX=D:\\DeskTopFile\\Control-VAE-main\\ModifyODESrc']' returned non-zero exit status 1.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by heyuanYao-pku** [comment]
Could you please try to pip uninstall setuptools and reinstall it with version ==58.2.0?

**Comment by heyuanYao-pku** [comment]
Due to no response, I have decided to close this issue. Currently, the code can be compiled on most machines (we have tried Win11, Mac, and Linux), but we cannot guarantee it will continue to work as environments update. For those who may encounter issues in the future, you might try specifying the version of the setuptools library and ensuring the version of Cython is 0.x.x.
